### ISSUE TITLE
为这个项目适配了一下open-ip-kvm

### ISSUE THREAD

**Issue by ElluIFX** [Jackadminx/KVM-Card-Mini#1]
https://github.com/ElluIFX/open-ip-kvm
多谢大佬的硬件实现

**Comment by Jackadminx** [comment]
谢谢，感谢对本项目的适配

**Comment by LXC1120** [comment]
> 

大佬请教一下，使用n1在armbian中部署了µStreamer、Node.js、ElluIFX/open-ip-kvm，但是执行npm run start提示报错，单独执行./ustreamer是可以运行ustreamer，能不能帮忙看下是什么问题啊？

root@armbian:~/open-ip-kvm# npm run start

> open-ip-kvm@1.0.0 start /root/open-ip-kvm
> sudo node server/index.js

TypeError: cannot open device with vendor id 0x413d and product id 0x2107
    at new HID (/root/open-ip-kvm/node_modules/node-hid/nodehid.js:49:17)
    at new HIDController (/root/open-ip-kvm/server/hid.js:38:23)
    at start (/root/open-ip-kvm/server/index.js:20:15)
    at Object.<anonymous> (/root/open-ip-kvm/server/index.js:100:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-ip-kvm@1.0.0 start: `sudo node server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-ip-kvm@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-12T00_57_28_225Z-debug.log

**Comment by ElluIFX** [comment]
> > 
> 
> 大佬请教一下，使用n1在armbian中部署了µStreamer、Node.js、ElluIFX/open-ip-kvm，但是执行npm run start提示报错，单独执行./ustreamer是可以运行ustreamer，能不能帮忙看下是什么问题啊？
> 
> root@armbian:~/open-ip-kvm# npm run start
> 
> > open-ip-kvm@1.0.0 start /root/open-ip-kvm
> > sudo node server/index.js
> 
> TypeError: cannot open device with vendor id 0x413d and product id 0x2107 at new HID (/root/open-ip-kvm/node_modules/node-hid/nodehid.js:49:17) at new HIDController (/root/open-ip-kvm/server/hid.js:38:23) at start (/root/open-ip-kvm/server/index.js:20:15) at Object. (/root/open-ip-kvm/server/index.js💯1) at Module._compile (internal/modules/cjs/loader.js:1068:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) at Module.load (internal/modules/cjs/loader.js:933:32) at Function.Module._load (internal/modules/cjs/loader.js:774:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! open-ip-kvm@1.0.0 start: `sudo node server/index.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the open-ip-kvm@1.0.0 start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2023-08-12T00_57_28_225Z-debug.log

报错不是很显然么，没找到设定的hid设备，可以lsusb看看是不是真的接入了
